#!/bin/sh

##
## Setup ASE environment using ../rtl/sources.txt.
##

# Absolute path to this script
SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")

afu_sim_setup --sources="${SCRIPT_PATH}/output/sources_sim.txt" --platform a10_gx_intg_xeon_bdx $@
